const SEAGRI_PESSOAS=[
  {id:"sec",setor:"Secretária",nome:"Temyllis Lima da Silva",grupo:"Secretaria",kind:"secretaria"},
  {id:"secad",setor:"Secretário Adjunto",nome:"Edivan Maciel",grupo:"Secretaria",kind:"secretaria-adjunta"},
  {id:"gab",setor:"Gabinete da Secretária",nome:"Francisco Diego",grupo:"Secretaria",kind:"assessoria"},
  {id:"gabsecad",setor:"Gabinete do Secretário Adjunto",nome:"Josilda Lima",grupo:"Secretaria",kind:"assessoria"},
  {id:"ci",setor:"Controle Interno",nome:"Lilian Vitoria",grupo:"Secretaria",kind:"assessoria"},
  {id:"conjur",setor:"Consultoria Jurídica",nome:"Thais Ferreira",grupo:"Secretaria",kind:"assessoria"},
  {id:"ascom",setor:"Assessoria de Comunicação",nome:"Dionisio Neto",grupo:"Secretaria",kind:"assessoria"},
  {id:"ouvid",setor:"Ouvidoria",nome:"Maria Socorro",grupo:"Secretaria",kind:"assessoria"},

  {id:"daf",setor:"Diretoria de Administração e Finanças",nome:"Nivia Cristina",grupo:"DAF",kind:"diretoria"},
  {id:"del",setor:"Departamento de Escritórios Locais",nome:"Jorge Ney Pontes",grupo:"DAF",kind:"departamento"},
  {id:"deg",setor:"Departamento de Gestão",nome:"Mayssa Diniz",grupo:"DAF",kind:"departamento"},
  {id:"deplan",setor:"Departamento de Planejamento",nome:"Natalia Cristina",grupo:"DAF",kind:"departamento"},
  {id:"deof",setor:"Departamento de Orçamento e Finanças",nome:"Heloneyda Marques",grupo:"DAF",kind:"departamento"},
  {id:"disg",setor:"Divisão de Serviços Gerais",nome:"Renata Carvalho",grupo:"DAF",kind:"divisao"},
  {id:"dipm",setor:"Divisão de Patrimônio e Materiais",nome:"Rosimeire Cavalcante",grupo:"DAF",kind:"divisao"},
  {id:"diarp",setor:"Divisão de Arquivo e Protocolo",nome:"Maria do Socorro",grupo:"DAF",kind:"divisao"},
  {id:"dirh",setor:"Divisão de Recursos Humanos",nome:"Marcleide Tavares",grupo:"DAF",kind:"divisao"},
  {id:"dit",setor:"Divisão de Transporte",nome:"Pedro Alencar",grupo:"DAF",kind:"divisao"},
  {id:"dimt",setor:"Divisão de Modernização Tecnológica",nome:"Luan Dourado",grupo:"DAF",kind:"divisao"},
  {id:"dicompras",setor:"Divisão de Licitações, Compras e Contratos",nome:"João Paulo",grupo:"DAF",kind:"divisao"},
  {id:"dicon",setor:"Divisão de Convênios",nome:"Pâmela Galvão",grupo:"DAF",kind:"divisao"},
  {id:"dipro",setor:"Divisão de Programas",nome:"Marcos Santana",grupo:"DAF",kind:"divisao"},
  {id:"dimon",setor:"Divisão de Monitoramento",nome:"Éllen Abud",grupo:"DAF",kind:"divisao"},
  {id:"dif",setor:"Divisão de Finanças",nome:"Karin Gomes",grupo:"DAF",kind:"divisao"},
  {id:"dic",setor:"Divisão de Contabilidade",nome:"Camila Arruda",grupo:"DAF",kind:"divisao"},

  {id:"dpa",setor:"Diretoria de Produção e Agronegócio",nome:"Cláudio Malveira",grupo:"DPA",kind:"diretoria"},
  {id:"desan",setor:"Departamento Socioprodutivo e Segurança Alimentar",nome:"Igor Honorato",grupo:"DPA",kind:"departamento"},
  {id:"deagro",setor:"Departamento de Agronegócio",nome:"Jalceyr Pessoa",grupo:"DPA",kind:"departamento"},
  {id:"deprof",setor:"Departamento de Produção Familiar",nome:"Josicley Azevedo",grupo:"DPA",kind:"departamento"},
  {id:"dem",setor:"Departamento de Mecanização",nome:"Richarler Aguiar",grupo:"DPA",kind:"departamento"},
  {id:"diis",setor:"Divisão de Inclusão Socioprodutiva",nome:"Ariane Gadelha",grupo:"DPA",kind:"divisao"},
  {id:"disan",setor:"Divisão de Segurança Alimentar",nome:"Marcela",grupo:"DPA",kind:"divisao"},
  {id:"dia",setor:"Divisão de Agricultura",nome:"Nilton Cesar",grupo:"DPA",kind:"divisao"},
  {id:"dipec",setor:"Divisão de Pecuária",nome:"Willian Junis",grupo:"DPA",kind:"divisao"},
  {id:"divpi",setor:"Divisão de Produção Indígena",nome:"Adriano Dias",grupo:"DPA",kind:"divisao"},
  {id:"divpf",setor:"Divisão de Produção Familiar",nome:"Wally Stanley",grupo:"DPA",kind:"divisao"},
  {id:"disbio",setor:"Divisão de Sociobiodiversidade",nome:"Eneide Thaumaturgo",grupo:"DPA",kind:"divisao"},
  {id:"nap",setor:"Núcleo de Apoio Logístico",nome:"Antônio José",grupo:"DPA",kind:"nucleo"},
  {id:"ncaf",setor:"Núcleo de Cadastro da Agricultura Familiar",nome:"Conceição",grupo:"DPA",kind:"nucleo"},
  {id:"npolo",setor:"Núcleo de Polos Agroflorestais",nome:"Carlos Antonio",grupo:"DPA",kind:"nucleo"},
  {id:"npaa",setor:"Núcleo do Programa de Aquisição de Alimentos",nome:"Claiton",grupo:"DPA",kind:"nucleo"},
  {id:"npaai",setor:"Núcleo do Programa de Aquisição de Alimentos Indígena",nome:"José Paulo",grupo:"DPA",kind:"nucleo"},
  {id:"npaaex",setor:"Núcleo do Programa de Aquisição de Alimentos Extrativista",nome:"Yanná",grupo:"DPA",kind:"nucleo"},
  {id:"nucaf",setor:"Núcleo do Café",nome:"Michelma Silva",grupo:"DPA",kind:"nucleo"},
  {id:"nuars",setor:"Núcleo de Armazenamento e Silos",nome:"Nilton César",grupo:"DPA",kind:"nucleo"},
  {id:"nuapes",setor:"Núcleo de Aquicultura e Pesca",nome:"Wallace Santos",grupo:"DPA",kind:"nucleo"},
  {id:"nuav",setor:"Núcleo da Avicultura",nome:"Bruna Diogo",grupo:"DPA",kind:"nucleo"},
  {id:"nuspi",setor:"Núcleo Socioprodutivo Indígena",nome:"Hidelk Farias",grupo:"DPA",kind:"nucleo"},
  {id:"nucac",setor:"Núcleo do Cacau",nome:"Marcos Rocha",grupo:"DPA",kind:"nucleo"},
  {id:"numel",setor:"Núcleo do Mel",nome:"Rubia Mara",grupo:"DPA",kind:"nucleo"},
  {id:"numan",setor:"Núcleo da Mandioca",nome:"Murilo Matos",grupo:"DPA",kind:"nucleo"},
  {id:"nuole",setor:"Núcleo da Olericultura",nome:"Adriana Melo",grupo:"DPA",kind:"nucleo"},
  {id:"nuex",setor:"Núcleo de Extrativismo",nome:"Angelina Lima",grupo:"DPA",kind:"nucleo"},

  {id:"dptec",setor:"Diretoria de Pesquisa, Tecnologia e Inovação do Agronegócio",nome:"Thiago de Almeida",grupo:"DPTEC",kind:"diretoria"},
  {id:"det",setor:"Departamento de Tecnologia",nome:"Luan Sobral",grupo:"DPTEC",kind:"departamento"},
  {id:"depi",setor:"Departamento de Pesquisa e Inovação",nome:"Roger Recco",grupo:"DPTEC",kind:"departamento"},
  {id:"digt",setor:"Divisão de Geoprocessamento e Telemetria",nome:"Izaura Cardoso",grupo:"DPTEC",kind:"divisao"},
  {id:"disoft",setor:"Divisão de Sistema de Informação",nome:"Gabriane Vaz",grupo:"DPTEC",kind:"divisao"},
  {id:"ditt",setor:"Divisão de Transferência de Tecnologia",nome:"Ediu Carlos",grupo:"DPTEC",kind:"divisao"},
  {id:"dipa",setor:"Divisão de Pesquisa Agropecuária",nome:"Marcos Vinicius",grupo:"DPTEC",kind:"divisao"},
  {id:"dicp",setor:"Divisão de Certificação de Produtos",nome:"Yanná Thaumaturgo",grupo:"DPTEC",kind:"divisao"},

  {id:"el-acld",setor:"Escritório Local de Acrelândia",nome:"Max Teodoro",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-abl",setor:"Escritório Local de Assis Brasil",nome:"Wilker Nazareno",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-bli",setor:"Escritório Local de Brasiléia",nome:"Antônio Francisco",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-bjri",setor:"Escritório Local de Bujari",nome:"Luciano Queiroz",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-cpxb",setor:"Escritório Local de Capixaba",nome:"Kemy Fernandes",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-czs",setor:"Escritório Local de Cruzeiro do Sul",nome:"Marcos Pereira",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-ept",setor:"Escritório Local de Epitaciolândia",nome:"Jose Menezes",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-fjo",setor:"Escritório Local de Feijó",nome:"João Paulo",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-pdht",setor:"Escritório Local do Humaitá",nome:"Wilson Brito",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-joao",setor:"Escritório Local de Jordão",nome:"Cintia Araujo",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-mli",setor:"Escritório Local de Mâncio Lima",nome:"Magno Corrêa",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-mlu",setor:"Escritório Local de Manoel Urbano",nome:"Denes Bruno",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-mlto",setor:"Escritório Local de Marechal Thaumaturgo",nome:"Laires Azevedo",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-poac",setor:"Escritório Local de Porto Acre",nome:"Wilson de Brito",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-pcy",setor:"Escritório Local de Plácido de Castro",nome:"Antonio Pinto",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-pwtr",setor:"Escritório Local de Porto Walter",nome:"Eriânio Melo",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-rbo",setor:"Escritório Local de Rio Branco",nome:"Risomar Freire",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-srju",setor:"Escritório Local de Santa Rosa do Purus",nome:"Lugma Fernanda",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-smd",setor:"Escritório Local de Sena Madureira",nome:"Adoneyson Campos",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-swd",setor:"Escritório Local de Senador Guiomard",nome:"Carlos Casas",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-tau",setor:"Escritório Local de Tarauacá",nome:"Leocélia Monteiro",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-trcr",setor:"Escritório Local da Transacreana",nome:"Lucas Paiva",grupo:"Escritórios Locais",kind:"escritorio"},
  {id:"el-xpi",setor:"Escritório Local de Xapuri",nome:"Antonio Alves",grupo:"Escritórios Locais",kind:"escritorio"}
];
